name: Setup
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 20.5.0
    - run: npm install --global npm@10.8.1
    - run: npm install --global yarn@1.22.22

