name: Setup
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 16
        registry-url: https://registry.npmjs.org
        cache: yarn

    - uses: actions/cache@v4
      id: install-cache
      with:
        path: node_modules/
        key: ${{ runner.os }}-install-${{ hashFiles('**/yarn.lock') }}

    - if: steps.install-cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile --ignore-scripts
      shell: bash

    - uses: gradle/gradle-build-action@v4
